### ISSUE TITLE
Possibly using modified Vichan default homepage instead of custom.

### ISSUE THREAD

**Issue by libruh2** [codingneko/vichan#5]
Vichan already has a built in homepage (check the themes option under mod management panel) and it might make the homepage more cohesive with the rest of the site if you were to add the current board listing and board creation options to one of these pre-existing templates instead.

**Comment by codingneko** [comment]
F lemme see

**Comment by codingneko** [comment]
Kek you're right fuck my life

**Comment by libruh2** [comment]
Don't get me wrong. You should embed the 8chan style board listing into the newer homepage, it looks pretty cool.
